---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:preview-add-support-for-cohere-model-in-aws-bedrock-23f58e3
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    environment:
      AWS_ACCESSKEY: $AWS_ACCESSKEY
      AWS_ACCESSSECRET: $AWS_ACCESSSECRET
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-aws'
      ENABLE_MODULES: 'text2vec-aws,generative-aws'
      CLUSTER_HOSTNAME: 'node1'
...